name: My Starter Workflow

on:
  workflow_dispatch:   # keep manual trigger if you want
  push:                # add push so a commit will also run the workflow automatically

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy to your project.

  call-reusable-workflow:
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      node: 14
